### PR TITLE
Handled Toaster, My orders and cart features

### PR DESCRIPTION
**Pull request by Naman-1234**
Features added:
- Toaster appears on checkout.
- Items were added dynamically and successfully on the My Orders page.
- Added some extra fields in cart items, So as to utilize them in my orders page.
- Added a page for showing the history of items sold by user.

### CODE REVIEW

**Review by nlok5923 — CHANGES_REQUESTED** [review]
Changes are fine just a little thing to note that we need to display the actual image of product not the logo.

not this 
image

Also please do remove this as well 
image

**Comment by nlok5923** [comment]
@Naman-1234 ptal

**Comment by Naman-1234** [comment]
Will do this tomorrow.
- Regarding the image of crypto, It is not the logo. I code it like if there is no picture of an item then this image acts as a kind of placeholder, But will check out why it is appearing in all.
- Will remove the buttons and Total Rs.
- Will add the shipping address.

**Comment by nlok5923** [comment]
Need actual images here:
> my orders page
image

here as well:
> your orders page
image

Also do checkout this image once i click on proceed to checkout it redirect me to success page but still the items are added in the cart and also the payment process is also not initiated.

https://drive.google.com/file/d/1-ph_ZGuRVvXoFpq9IKKUJhSDduFpA6nY/view?usp=sharing

**Comment by Naman-1234** [comment]
@nlok5923, Please try again and also your internet connection, On my end, it is working nicely.Also that redirection for success page is fixed now.
Please find the below video as a reference

https://user-images.githubusercontent.com/63748249/141454588-d5d0c4f0-6f88-4445-bfcd-29806a7d63f3.mp4

.

**Pull request merged**
